server:
  port: 8081
  
spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true         

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

management:
  health:
   circuitbreakers:
    enabled: true

  endpoints:
   web:
    exposure: 
     include: health

  endpoint:
   health:
    show-details: always   

resilience4j:
  circuitbreaker:
    instances:
      accountTransactionBreaker:
       registerHealthIndicator: true
       eventConsumerBufferSize: 10
       failureRateThreshold: 50
       minimumNumberOfCalls: 5
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 6s
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowSize: 10
       slidingWindowType: COUNT_BASED