server:
  port: 8083

spring:
  application:
    name: Transaction-Service

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true   

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/          
